
package com.epam.task02.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRandomNumberer", targetNamespace = "http://service.task02.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRandomNumberer {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRandomNumber", targetNamespace = "http://service.task02.epam.com/", className = "com.epam.task02.service.GetRandomNumber")
    @ResponseWrapper(localName = "getRandomNumberResponse", targetNamespace = "http://service.task02.epam.com/", className = "com.epam.task02.service.GetRandomNumberResponse")
    @Action(input = "http://service.task02.epam.com/IRandomNumberer/getRandomNumberRequest", output = "http://service.task02.epam.com/IRandomNumberer/getRandomNumberResponse")
    public int getRandomNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
